allowBuilds:
  electron-nightly: true
  electron-winstaller: true
  fs-xattr: true
  macos-alias: true

overrides:
  "@electron-forge/maker-base": "^8.0.0-0"
  "@electron-forge/publisher-base": "^8.0.0-0"
  # https://github.com/max-mapper/extract-zip/issues/154
  "yauzl": "3.3.1"

blockExoticSubdeps: false

nodeLinker: hoisted # :(
