const possibleSplashFlavors: string[] = [
	'Innovative Splash Text!',
	'Contribute On Github!',
	'Pretty Slick, NGL.',
	'Back Again?',
	'Get That Nuke!',
	'At Least 10 FPS.',
	'Slidehopping Into Your DMs.',
	'Raining On Their Parade.',
	'Buy Kraxen A Coffee!',
	'Splish Splash.',
	'Are We Back?',
	'Farming Wallbangs.',
	'Joke About Shotgun Players',
	'Loading The Worst Person Shooter...',
	'Are We Loading?',
	'Pro Tip: WASD To Move.',
	'Masters Degree In Krunker.',
	'UNLOADING...',
	'Switching To Your Secondary Is Faster!',
	'let const var magicNumber = 3;',
	'Spawning Players...',
	'Finding a Lobby...',
	'Making Everything Framerate-Dependent...',
	'Giving You Brain Damage Since 2018.',
	'Setting Slide Control To 5...',
	'Sawing Off The Shotgun...',
	'Crying About Sniper...',
	'A-ing The K47...',
	'Jumping Off The Walls...',
	'Nerfing Akimbo Uzis...',
	'Complaining About Blaster...',
	'Buying Mastery Skins...',
	'Reaching Level 100 Runner...',
	'Farming Twitch Drops...',
	'Using Boulder...',
	'Having Revelations...',
	'Writing New Shaders...',
	"He's Doing It Sideways!",
	'AFKing Trade Lobbies...',
	'Going nuclear...',
	'You Should Clanhop!',
	'Lobbyhopping!',
	'Hitting a One-Burst...',
	'Hup!',
	'What mod are you using?',
	'BOOM HEADSHOT!',
	'Everyone runs faster with a knife!',
	'Everyone knows that!',
	'Open Source!',
	'40% Packet Loss',
	'Woah Mama!',
	'Flatline!',
	'RETIRED!',
	'Breakcore is a real genre!',
	'Not the car part.',
	'Userscripts are sweet!',
	'Learn Typescript Today!',
	'Use the Custom Matchmaker!',
	"I CAN'T COMPETE!",
	'dude...',
	'Also Try Terraria!',
	'Also Try Minecraft!',
	'Shift Space Shift Space...',
	'Fragging Out!',
	'Intelligent?',
	'Level 100 Yet?',
	'The grind never stops!',
	'Sleep is for the weak.',
	'CAFFEINE.',
	'Could use more hot sauce.',
	'A shrimp fried this rice?',
	'Wood fired pizza?!',
	"How's pizza gonna get a job now?!",
	'230hp LMG',
	'Full Auto.',
	'Fuller Auto.',
	'Triggerman vs. Doom Guy',
	'Check Trades.',
	'Posture Check',
	'Remember to drink water!',
	'Get up and stretch every 30-40 minutes.',
	"Killstreaks don't matter.",
	'Are you on the grind?',
	'Grass Status: touched.',
	'UwU',
	'Breakfast of Champions.',
	'Sleep if you need it!',
	"You'll never understand this joke.",
	"You just lost 'The Game'",
	'Playing 4D Chess.',
	'Hey you hungry home invader!',
	'Did you leave your refrigerator running?',
	'Sayonara!',
	"I wouldn't touch that if I were you.",
	'Funny Green Rock.',
	'Vocabulary',
	'0.2 W/L',
	"Stats don't matter.",
	"Don't sweat it!",
	'Input Failed 3',
	'Brian from Krunker',
	'525',
	'novisgravitas',
	'Freezing Aim...',
	'Nyoom',
	'Colon Three',
	'Shrimply Mantastic',
	'Now with cloudy skies!',
	"There's so much to look forward to!",
	"What's gonna work? Teamwork!",
	'Krunkin into the sunset',
	'Is this thing on?',
	'Withered flowers forget!',
	"That aint' workin?",
	'ALL SYSTEMS NOMINAL.',
	'The powerhous of the cell.',
	"I've got nothing to say.",
	'>:)',
	'Hi Mom!',
	'Great Vegetables.',
	"Don't throw in the trowel!",
	'Breaking the world!',
	'Honestly Quite Incredible',
	'Dodge this.',
	'Spills the beans.',
	'Wage war against frogs!',
	'Can you kill the rabbits?',
	'Idol of the idle.',
	'Everything is dull and dry.',
	'Thank you my twilight!',
	'An antidote for thinking.',
	"That's just like your opinion, man.",
	'Biting my tongue.',
	'Hands of time.',
	'12 dumbass scientists.',
	'The enemy of art.',
	'Shots 1-5',
	'Take up your brush!',
	"It's a cylinder.",
	'A lot of things can save us today.',
	'Now I can talk!',
	'A fool and his money.',
	"I can't get a grip.",
	"You're no fun!",
	"It's like Halo 2 meets Halo 3.",
	'I liked it.',
	"Nothing is foolproof.",
	'We came here to fight each other.',
	'Abandon all hope.',
	'Fly like an eagle...',
	'Dancing. Walking.',
	'ooo eee ooo',
	'Novel yet familiar.',
	'Oh no! Anyways...',
	'Bapanada.',
	'I count 6 shots.',
	'Forklift Certified.',
	'...is not a palendrome.',
	'Big if true.',
	'Evasive maneuvers!',
	"I'm the main character!",
	'Da svidaniya, darling!',
	'SI SI SI SI SI',
	'Who up?',
	'rest in peace, Boo'
];

const splashFlavor = possibleSplashFlavors[Math.floor(Math.random() * possibleSplashFlavors.length)];

export { splashFlavor };
