const possibleSplashFlavors: string[] = [
	'Innovative Splash Text!',
	'Contribute On Github!',
	'Pretty Slick, NGL.',
	'Back Again?',
	'Get That Nuke!',
	'At Least 10 FPS.',
	'Slidehopping Into Your DMs.',
	'Raining On Their Parade.',
	'Buy Kraxen A Coffee!',
	'Splish Splash.',
	'Are We Back?',
	'Farming Wallbangs.',
	'Joke About Shotgun Players',
	'Loading The Worst Person Shooter...',
	'Are We Loading?',
	'Pro Tip: WASD To Move.',
	'Masters Degree In Krunker.',
	'Deleting System32...',
	'UNLOADING...',
	'Switching To Your Secondary Is Faster!',
	'let const var magicNumber = 3;',
	'Spawning Players...',
	'Finding a Lobby...',
	'Making Everything Framerate-Dependent...',
	'Giving You Brain Damage Since 2018.',
	'Setting Slide Control To 5...',
	'Sawing Off The Shotgun...',
	'Crying About Sniper...',
	'A-ing The K47...',
	'Jumping Off The Walls...',
	'Nerfing Akimbo Uzis...',
	'Complaining About Blaster...',
	'Buying Mastery Skins...',
	'Reaching Level 100 Runner...',
	'Farming Twitch Drops...',
	'Using Boulder...',
	'Having Revelations...',
	'Writing New Shaders...',
	"He's Doing It Sideways!",
	'AFKing Trade Lobbies...'
];

const splashFlavor = possibleSplashFlavors[Math.floor(Math.random() * possibleSplashFlavors.length)];

export { splashFlavor };
